<?php
namespace Avalonia\Win32\DirectX;
/**
 */
enum DXGI_SWAP_CHAIN_FLAG implements 
	\System\IComparable,
	\System\IFormattable,
	\System\IConvertible
{
	case DXGI_SWAP_CHAIN_FLAG_NONPREROTATED = 1;
	case DXGI_SWAP_CHAIN_FLAG_ALLOW_MODE_SWITCH = 2;
	case DXGI_SWAP_CHAIN_FLAG_GDI_COMPATIBLE = 4;
	case DXGI_SWAP_CHAIN_FLAG_RESTRICTED_CONTENT = 8;
	case DXGI_SWAP_CHAIN_FLAG_RESTRICT_SHARED_RESOURCE_DRIVER = 16;
	case DXGI_SWAP_CHAIN_FLAG_DISPLAY_ONLY = 32;
	case DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT = 64;
	case DXGI_SWAP_CHAIN_FLAG_FOREGROUND_LAYER = 128;
	case DXGI_SWAP_CHAIN_FLAG_FULLSCREEN_VIDEO = 256;
	case DXGI_SWAP_CHAIN_FLAG_YUV_VIDEO = 512;
	case DXGI_SWAP_CHAIN_FLAG_HW_PROTECTED = 1024;
	case DXGI_SWAP_CHAIN_FLAG_ALLOW_TEARING = 2048;
	case DXGI_SWAP_CHAIN_FLAG_RESTRICTED_TO_ALL_HOLOGRAPHIC_DISPLAYS = 4096;
}
