<Project>
  
  <PropertyGroup>
    <!-- version -->
    <AvaloniaVersion>12.0.0</AvaloniaVersion>
    <PeachpieVersion>1.1.13</PeachpieVersion>
    <SystemDrawingCommonVersion>10.0.7</SystemDrawingCommonVersion>
    <TmdsDBusProtocolVersion>0.92.0</TmdsDBusProtocolVersion>
    <Version Condition=" '$(Version)'=='' ">1.0.4</Version>
    <PackageVersion>$(Version)</PackageVersion>
    <TargetFrameworkVersion>net10.0</TargetFrameworkVersion>
    <!-- Using private apis in nuget packages -->
    <AvaloniaAccessUnstablePrivateApis>true</AvaloniaAccessUnstablePrivateApis>
    <Avalonia_I_Want_To_Use_Private_Apis_In_Nuget_Package_And_Promise_To_Pin_The_Exact_Avalonia_Version_In_Package_Dependency>true</Avalonia_I_Want_To_Use_Private_Apis_In_Nuget_Package_And_Promise_To_Pin_The_Exact_Avalonia_Version_In_Package_Dependency>
    <!-- metadata generation -->
    <GenerateAssemblyVersionAttribute>true</GenerateAssemblyVersionAttribute>
    <GenerateAssemblyFileVersionAttribute>true</GenerateAssemblyFileVersionAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateNeutralResourcesLanguageAttribute>true</GenerateNeutralResourcesLanguageAttribute>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <LangVersion>latest</LangVersion>
    <GenerateFullPaths>true</GenerateFullPaths>
    <DefineConstants>$(DefineConstants);TRACE</DefineConstants>
    
    <!-- signing 
    <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)build/</AssemblyOriginatorKeyFile>
    <SignAssembly>true</SignAssembly> 
    -->
    
  </PropertyGroup>

  <!-- package -->
  <PropertyGroup>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/FibonacciFox/Peachpie.Avalonia</RepositoryUrl>
    <PackageProjectUrl>https://github.com/FibonacciFox/Peachpie.Avalonia</PackageProjectUrl>
    <PackageOutputPath Condition=" '$(PackageOutputPath)'=='' ">$(MSBuildThisFileDirectory).nuget</PackageOutputPath>
    <PackageIcon>logo_en.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Authors>FibonacciFox</Authors>
    <NoWarn>AVA3001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="" Link="README.md" />
    <None Include="$(MSBuildThisFileDirectory)docs/logo/logo_en.png" Pack="true" PackagePath="" Link="logo_en.png" />
  </ItemGroup>
  
</Project>
