<?php
namespace Avalonia\Win32\WinRT;
/**
 */
enum GRAPHICS_EFFECT_PROPERTY_MAPPING implements 
	\System\IComparable,
	\System\IFormattable,
	\System\IConvertible
{
	case GRAPHICS_EFFECT_PROPERTY_MAPPING_UNKNOWN = 0;
	case GRAPHICS_EFFECT_PROPERTY_MAPPING_DIRECT = 1;
	case GRAPHICS_EFFECT_PROPERTY_MAPPING_VECTORX = 2;
	case GRAPHICS_EFFECT_PROPERTY_MAPPING_VECTORY = 3;
	case GRAPHICS_EFFECT_PROPERTY_MAPPING_VECTORZ = 4;
	case GRAPHICS_EFFECT_PROPERTY_MAPPING_VECTORW = 5;
	case GRAPHICS_EFFECT_PROPERTY_MAPPING_RECT_TO_VECTOR4 = 6;
	case GRAPHICS_EFFECT_PROPERTY_MAPPING_RADIANS_TO_DEGREES = 7;
	case GRAPHICS_EFFECT_PROPERTY_MAPPING_COLORMATRIX_ALPHA_MODE = 8;
	case GRAPHICS_EFFECT_PROPERTY_MAPPING_COLOR_TO_VECTOR3 = 9;
	case GRAPHICS_EFFECT_PROPERTY_MAPPING_COLOR_TO_VECTOR4 = 10;
}
