<?php
namespace Avalonia\FreeDesktop\DBusIme\Fcitx;
/**
 */
enum FcitxCapabilityFlags implements 
	\System\IComparable,
	\System\IFormattable,
	\System\IConvertible
{
	case CAPACITY_NONE = 0;
	case CAPACITY_CLIENT_SIDE_UI = 1;
	case CAPACITY_PREEDIT = 2;
	case CAPACITY_CLIENT_SIDE_CONTROL_STATE = 4;
	case CAPACITY_PASSWORD = 8;
	case CAPACITY_FORMATTED_PREEDIT = 16;
	case CAPACITY_CLIENT_UNFOCUS_COMMIT = 32;
	case CAPACITY_SURROUNDING_TEXT = 64;
	case CAPACITY_EMAIL = 128;
	case CAPACITY_DIGIT = 256;
	case CAPACITY_UPPERCASE = 512;
	case CAPACITY_LOWERCASE = 1024;
	case CAPACITY_NOAUTOUPPERCASE = 2048;
	case CAPACITY_URL = 4096;
	case CAPACITY_DIALABLE = 8192;
	case CAPACITY_NUMBER = 16384;
	case CAPACITY_NO_ON_SCREEN_KEYBOARD = 32768;
	case CAPACITY_SPELLCHECK = 65536;
	case CAPACITY_NO_SPELLCHECK = 131072;
	case CAPACITY_WORD_COMPLETION = 262144;
	case CAPACITY_UPPERCASE_WORDS = 524288;
	case CAPACITY_UPPERCASE_SENTENCES = 1048576;
	case CAPACITY_ALPHA = 2097152;
	case CAPACITY_NAME = 4194304;
	case CAPACITY_GET_IM_INFO_ON_FOCUS = 8388608;
	case CAPACITY_RELATIVE_CURSOR_RECT = 16777216;
}
