name: Package Create & Publish

on:
  push:
    branches: [ "master" ]
  
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install dependencies
        run: dotnet restore Peachpie.Avalonia.sln

      - name: Build
        run: dotnet build Peachpie.Avalonia.sln --configuration Release --no-restore

      - name: Publish NuGet Package
        run: dotnet nuget push .nuget/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
